version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DB_STRING=${DB_STRING}
      - AWS_S3_PREFIX=${AWS_S3_PREFIX}
      - AWS_PREFIX=${AWS_PREFIX}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - GOOGLE_MAIL=${GOOGLE_MAIL}
      - SMTP_HOST=${SMTP_HOST}
      - APP_PASSWORD=${APP_PASSWORD}
      - NODEMAILER_EMAIL=${NODEMAILER_EMAIL}