version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_STRING
      - API_KEY
      - AWS_S3_PREFIX
      - AWS_PREFIX
      - AWS_BUCKET_NAME
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - GOOGLE_EMAIL
      - SMTP_HOST
      - APP_PASSWORD
      - NODEMAILER_EMAIL


    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html:ro
    depends_on:
      - app
